server.port: 8080
spring.application.name: users-ws

eureka.client.serviceUrl.defaultZone: http://${discovery.server.userName}:${discovery.server.password}@${discovery.server.host}:${discovery.server.port}/eureka
eureka.instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring.devtools.restart.enabled: true