
server.port: 8080
spring.application.name: feed-service-ws

spring.data.mongodb:
  host: localhost
  port: 27017


logging.level:
  org.springframework.data.elasticsearch.core: DEBUG
  org.springframework.data.elasticsearch.repository: DEBUG
  org.springframework.data.repository: DEBUG
  tracer: TRACE