
spring.data.mongodb:
  host: localhost
  port: 27017
  auto-index-creation: true

token:
  expiration_time: 864000000
  secret: ${jwt.token.secret}

authorization.token.header:
  name: Authorization
  prefix: Bearer

discovery.server:
  host: localhost
  port: 8010

api.login.url.path: /api/users/login
api.registration.url.path: /api/users

logging.level:
  org.springframework.data.elasticsearch.core: DEBUG
  org.springframework.data.elasticsearch.repository: DEBUG
  org.springframework.data.repository: DEBUG
  tracer: TRACE